language: c
 
install:
  - echo 'deb http://download.opensuse.org/repositories/home:tpokorra:mono/xUbuntu_13.04/ /' >> /etc/apt/sources.list.d/monodevelop-opt.list 
  - sudo apt-get update && sudo apt-get dist-upgrade
  - sudo apt-get install mono-devel mono-gmcs nunit-console
  - mozroots --import --sync
 
script:
  - xbuild ./src/DevAchievements.sln
  - nunit-console ./src/DevAchievements.Domain.UnitTests/bin/Debug/DevAchievements.Domain.UnitTests.dll ./src/DevAchievements.Infrastructure.AchievementProviders.FunctionalTests/bin/Debug/DevAchievements.Infrastructure.AchievementProviders.FunctionalTests.dll
