language: c
 
install:
  - sudo apt-get install monodevelop-latest mono-gmcs nunit-console
  - mozroots --import --sync
 
script:
  - xbuild ./src/DevAchievements.sln
  - nunit-console ./src/DevAchievements.Domain.UnitTests/bin/Debug/DevAchievements.Domain.UnitTests.dll ./src/DevAchievements.Infrastructure.AchievementProviders.FunctionalTests/bin/Debug/DevAchievements.Infrastructure.AchievementProviders.FunctionalTests.dll
